### ISSUE TITLE
Error in data frame dimensions

### ISSUE THREAD

**Issue by mvanrongen** [tavareshugo/R-intro-Cambridge-SysBio#3]
On the [Extra practice exercises](https://tavareshugo.github.io/r-intro-tidyverse-gapminder/90-appendix-exercises/index.html) page > Part II - reading and checking quality of data it mentions that the `gapminder1990to2010_energy.tsv` file contains 3968 rows and 7 columns. This is not correct with the current file given, it has fewer rows and only 6 columns. The dimensions may be hard-coded. If so, generating them automatically would probably be better.

**Comment by tavareshugo** [comment]
moved [here](https://github.com/tavareshugo/r-intro-tidyverse-gapminder/issues/9)
